### ISSUE TITLE
NG Bridge Image

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#10]
In the winter image there is one slope with some extra thicc outlines, tbd if the track itself is offset or just the outline

**Comment by Leartin** [comment]
Double Outline within the graphic

**Comment by Citarofahrer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bridge image](https://trello.com/c/lBDOnUAJ/4-bridge-image)
