### ISSUE TITLE
ADD NG Train Adler

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#11]
May or may not hit the current design standards, but would fit in well.
Should not be a lot of work to add this.

**Comment by Leartin** [comment]
If adapted for NG, perhaps change name to "Pfeil" for better differentiation?

**Comment by Flemmbrav** [comment]
https://de.wikipedia.org/wiki/ZB_ABeh_150
oh my bad, it's about that thingy :S

**Comment by Citarofahrer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ADD Train ZB ADLER](https://trello.com/c/YqCOIPmK/3-add-train-zb-adler)

**Comment by Flemmbrav** [comment]
https://github.com/Flemmbrav/Pak192.Comic/commit/8c88db589f474dd48b0d519edc7e4cdcc9bb3ab1
Done with that commit
