### ISSUE TITLE
merge alcoholic beverages

### ISSUE THREAD

**Issue by Leartin** [Flemmbrav/Pak192.Comic#15]
The pakset contains three types of alcohol right now (beer, wine, rum) and the cider press was intended to produce alcohol as well (cider/Most), and it probably won't end there. Therefore, should these goods be combined into just one good - alcohol?

**Comment by gpcf** [comment]
IMHO these should be kept separate – I found it fun to have container trains have many different colors of containers on them.

**Comment by Flemmbrav** [comment]
How many colours do you think containers should have?
Should we try to to bring that aspect to different goods too? 
I'm generally curious about this, don't take the answers for this for granted ;)

The idea of moving goods out of the piece goods category is a thing for a while now, mostly so the play can't just have all their vehicles to be the very same. 


We currently have quite some goods for containers:

Beer - could be a drink (additional to milk) OR alcohol
Coca Leaves - could as well be in the agrar category
Coka Drink - could be a drink (additional to milk)
Electronics
Ironmongery
Light Bulbs
Paint - could be in oil
Rum - could be a drink (additional to milk) OR alcohol
Sausages - could be cooled too
Berries - could as well be in the agrar category
Cable - could be a special freigth too
Car Parts
Comic Books
Fiber - could as well be in the agrar category
Flour - could as well be in the agrar category
Furniture
Honey - not currently used
Ingot
Juice - could be a drink (additional to milk)
Paper
Textiles
Toys
Vine - could be a drink (additional to milk) OR alcohol
Wax - not currently used


Wich leaves 11 different goods for containers (Electronics, Ironmonery, Light Bulbs, Car Parts, Comic Books, Furniture, Ingot, Paper, Textiles and Toys) plus the two unused ones (Wax and Honey).

What do you think? :S

**Comment by Leartin** [comment]
That's actually where this issue creeped up again, when I wanted to design containers for each good. You can expect them to not only have randomly different colors, but some designs too. 
For a while now, we were thinking on how to reduce the number of piece goods, since it feels like there are too many, and there number will be growing. There are some ideas so far:

1) **liquid food**. Instead of merging alcohol as one good, we could create a drink-category and have all alcohol as well as juice, coke and milk be transported in tank wagons. Obviously it's a bit far fetched, as that would kind of mean that they would be filled into bottles/cans/bags at the consumer. Simply merging all alcohol is the the more sensical option for this, though it's a comic pakset, sense is not strictly required.

2) **rolled goods**. Starting with the sheet metal coils, this idea is to exclude goods that are usually/often rolled for transport. Of the existing goods, this would be coils, cable, paper and 'textiles'. Further rolled goods could be yarn, carpet, chains, plastic wrap,...
This is pretty straightforward as transporters for coils could be reused with different loading graphics.

3) **split container goods from pallet goods**. That's a big one and kind of splits up industrial goods from consumer goods. car parts and furniture would be transported in containers, while comic books - delivered to a small comic book store, mind - would not. (In a time before modern containers, we'd use wooden boxes to represent them). The worst issue here is that changing from "pallets" to "containers" would mean that vehicles would transport about 1/10th, and factories would produce about 1/10th (since there are about 10 pallets in a 20' container). Vehicles would mostly carry but one or two containers, it could not be half a container. Storage space on stations is an issue, as it's the same for each good. It's okay to assume a cubic meter, a ton and a pallet requires about the same space, but a container is a different matter alltogether. And of course, new vehicles are required, and the number of different colored containers reduced.

(Flemmbrav: I don't think Ingots are actually in use, as it's coils and billets. Honey is now sold at the farmers market. Flour would not be 'light bulk', but a pourable good, if not transported in sacks)

**Comment by gpcf** [comment]
Juice should only be treated as liquid food if it's delivered to some other factory for processing, otherwise as piece goods, same thing with alcohol.

I would also reduce the demand of certain industries extremely, such as the pub and various markets, but make them spawn way more often, so local piece goods trains are needed.

**Comment by Leartin** [comment]
Current state of affairs:

Rolled goods are a reality now.

The current consideration for alcohol is having three goods - beer, wine, liquor. Cider would become wine, rum is liquor. This allows for many different alcohol producers without having too many goods, while keeping a nice variety.

No progress on containers so far. Probably won't happen unless the game changes.

**Comment by Flemmbrav** [comment]
Weird Idea: we could make a new Category for alcohol and transport them in barrels.

**Comment by Flemmbrav** [comment]
> No progress on containers so far. Probably won't happen unless the game changes.

I'd like to touch on that again, before we close this issue:

We changed a couple of goods during the current patch. We also changed the way the rafinery works, resulting in old saves not being compatible with the current pakset.
If we're to change good even further, i believe that the time for that is now.

**Comment by Leartin** [comment]
Certainly. IF we do it, then we do it before the next major release. I'll start a project later for a better overview.

**Comment by Flemmbrav** [comment]
I'll close this issues as we have barrels as a new category in use for alcohol right now.
There are also only three kinds of alcohol left in the game: Beer, Wine and Liquor.
With that, we can provide all three kinds of alcohol in almost every climate while still keeping some diversity. There's also plenty of room to provide different kinds of wine and liquor in different regions.
