### ISSUE TITLE
Compile error on Linux

### ISSUE THREAD

**Issue by vzrenggamani** [Flemmbrav/Pak192.Comic#16]
## Shown Error

> rengga_prakoso@cloudshell:~/Pak192.Comic (sakura-fukoka-studio-core)$ bash COMPILE.sh
> pak192.comic open-source repository compiler for Linux`
>
> This bash compiles this repository into a new folder called compiled, makeobj must be in root folder.
> Checking for makeobj... OK
> 
> Compiling Landscape...
> Error: Makeobj returned an error for pakset/landscape/ground/climatexture.dat. Aborting...

# Environment

Compiled on : Google Cloud Shell Default Image
Commit version : 03e7f53
Known COMPILER : `COMPILE.sh`

# Known Issues

Just looking at `pakset/landscape/ground/climatexture.dat` but idk what should i do

# Know solution

Still finding
`

**Comment by Flemmbrav** [comment]
Someone else ran into this before, I'll try to ask them how exacxtly they fixed it.
Back then they said that they were missing a lirary for makeobj.

**Comment by Flemmbrav** [comment]
Solution is to update the unix makeobj manually.
I will remove the not working file from the git.
Additionally there is an automatic nightly building service now, so there really is no need to have a way to build for lazy people.
