### ISSUE TITLE
Complying with the license: issues with Attribution.

### ISSUE THREAD

**Issue by Roboron3042** [Flemmbrav/Pak192.Comic#24]
The CC BY-SA 3.0 specifies the following

**Attribution**

**You must give appropriate credit,** provide a link to the license, and indicate if changes were made. [...]

However, when complying with this license I've found that... I don't know who I should credit. This repository does not specify who are the author(s) of this Work, and I can't find any names in the files. It is kind of violating his own license.
If you have a list of people who have participated in the project, I suggest you upload the list to the repository and link to it in the README.
Otherwise another solution is to ask in the README to credit "the pak192.comic team" when complying with the Attribution of this Work.

**Comment by Flemmbrav** [comment]
Almost every dat has a name behind "copyright=".
In plus you're right, we should add that everything that is not specified, is made by the whole team.
How would you declare that? As a last point in the README? Would you mention the license as well, or just add "In case it's not further specified, the author of the content is the pak192.comic-team"?

**Comment by Roboron3042** [comment]
Honestly, I only checked some random .dat files like pakset/UI/192/Cursors.dat and unfortunately I didn't see the "copyright=" in any xD

But yes, a section called "Attribution" or "License" at the end of the README including the license and this clarification would be sufficient.

**Comment by Flemmbrav** [comment]
I think every object that used to have the copyright displayed ingame has one as well (vehicles and buildings). Simutrans opened up on this and displays the copyrights of infrastructure now too, not sure if they have it too.

I'll add something like that tomorrow, thanks a lot for the feedback!

**Comment by Leartin** [comment]
> However, when complying with this license I've found that... I don't know who I should credit. This repository does not specify who are the author(s) of this Work, and I can't find any names in the files. It is kind of violating his own license.

Not quite. The CC-BY-SA license requires you, as an outsider, to name the authors of the works as they are given. It does not require an author to sign their original work. Doing so is essentially a less strict license than CC-BY-SA that's still compatible, just like CC0 is compatible. Eg. Sounds I added were all CC0.

If you take the pakset as a whole, the author information within the dat files or, respectively, within the game are sufficient, because that's what is provided. You are just not allowed to remove an author, even if you alter their work.

Note also that the CC-BY-SA license is for the outside world. Internally, we reuse each others content without attribution, otherwise you'd have three authors per object at average. This does not break cc-by-sa since it's just a case of dual licensing.

But I agree that it should be declared that if it comes to the whole thing, attributing it to the team is sufficient.

**Comment by Roboron3042** [comment]
> Not quite. The CC-BY-SA license requires you, as an outsider, to name the authors of the works as they are given. It does not require an author to sign their original work. 

I wasn't asking about signing all the work, just provide a list of authors, which is not the same.

> If you take the pakset as a whole, the author information within the dat files or, respectively, within the game are sufficient, because that's what is provided.

That's ok, but it's not obvious that this information is provided. As mentioned, I first thought that no authors were given after reviewing some files. Of course the license allows me to say "no author provided" if no author were given (which kind of defies the purpose of this license, but well xD), but in doing so as a whole I would be infringing the license by mistake, because authors were given, just not specified in a clear way for the redistributor.

**Comment by Leartin** [comment]
You implied that the license is violated by a lack of a named author - that's what my answer referred to. I don't disagree with a list of contributors, nor with a statement to use "pak192.comic team". 

Not naming an author does not defie the purpose of the license. The purpose of the license always was to ensure that this pakset can be developed further even if all team members disappear. The SA aspect is important in this regard to future-proof the idea, the BY-aspect merely a BY-product. (CC-SA does not exist). It's meant to be a copyleft license, but for art, not for code.

**Comment by Roboron3042** [comment]
I mean, your reasons to use this license and the license purposes may not align 100%, but it's called BY for a reason, and the Attribution term is as important as the SA one. We have make it easy to honour it.

Anyway, mi initial issue has been acknowledged, so I see no point in following the discussion.

Thank you.

**Comment by Flemmbrav** [comment]
I see nothing wrong using a licence that was not designed with this in mind, as long as it fits our case.
Also no one has to make it easy to honor it. If you can't honor it, you can't use it, that's all there is. 

I did edit the README.md in https://github.com/Flemmbrav/Pak192.Comic/commit/66b318aa9df9611f0c02f57a633d74290c6d9e23

**Comment by Roboron3042** [comment]
@Flemmbrav Do you know you can reference issues and PR in the commits? When committing, make sure to put the identifier (#number) of the issue/PR in the title, et voilà! It is automatically linked and displayed in the issue/PR history.

**Comment by Flemmbrav** [comment]
I thought so - just didn't end up finding it, thanks a lot!
