### ISSUE TITLE
Pakset Not Compiling On Two Old Patches

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#25]
Error in the Git-action is

> Update binaries of Nightly Release
2s
##[error]Node run failed with exit code 1
Run svenstaro/upload-release-action@v1-release
##[error]Error saving asset
##[error]Node run failed with exit code 1
>
For some reasons this only affects the build **without** the dat converter, even though i've changed the dat converter.

See https://github.com/Flemmbrav/Pak192.Comic/commit/f89016e29136af2a791eb95d45a9b9ce9c343bd8

**Comment by Flemmbrav** [comment]
Apparently https://github.com/Flemmbrav/Pak192.Comic/commit/a4eefa2f930f0e502f791a180f6c0987b15c5dff fixed it? I still have no clue how and why, this is just black magic.

**Comment by Leartin** [comment]
No. I don't think the code was broken in the first place.

**Comment by Flemmbrav** [comment]
So should I close this issue now? How do we want to deal with it? And do we?

**Comment by Flemmbrav** [comment]
With https://github.com/Flemmbrav/Pak192.Comic/commit/2144a8be55421896b8dc18b018b7a9e77875571f I've changed the vehicles a bit, and suddenly the theme doesn't compile any more. The whole thing really feels confusing to me. Maybe we have too many actions total, or in a single file?

**Comment by Flemmbrav** [comment]
This hasn't happened in a while, I'll close this issue now
