### ISSUE TITLE
Passenger train cars not couplable

### ISSUE THREAD

**Issue by gpcf** [Flemmbrav/Pak192.Comic#29]
It seems like most passenger cars cannot be coupled to each other.

**Comment by Flemmbrav** [comment]
Can you send me a screenshot of your Depot after buying the first car/loco?

This could be related to the introduction of the constraint[prev][0]=any string for most rail cars.

**Comment by Leartin** [comment]
It most likely is - gpcf, are you using the latest release? 
The "any" parameter should work with 121.0 (Revision 8870), the latest full version.

**Comment by gpcf** [comment]
this goes away when using 121.0.
