### ISSUE TITLE
Segfault when clicking "Silberling Lazarettwagen"

### ISSUE THREAD

**Issue by gpcf** [Flemmbrav/Pak192.Comic#31]
The game segfaults when I click the Silberling ambulance car. I'm running the current git version of simutrans on linux amd64.

**Comment by Flemmbrav** [comment]
Should already fixed in this: https://github.com/Flemmbrav/Pak192.Comic/commit/278ff28e8b2a2197ecf458854af6638fdbd687cb
Can you try downloading a newer nightly?

**Comment by gpcf** [comment]
Problem solved – was fixed in between me noticing the problem and me opening the issue :)

**Comment by Flemmbrav** [comment]
This one really is on me, I should have said some words in the bugfixing commit
