### ISSUE TITLE
Hamburg Subway does not build

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#36]

**Comment by Leartin** [comment]
All 19 of the Hamburg Subway vehicles were buildt and are in the zip file. Did you forget to electrify depot?

**Comment by Flemmbrav** [comment]
In the console we get this error:

`` ------------------------------------------------------``

``Compiling German Vehicles...``

``tput: No value for $TERM and no -T specified``
``tput: No value for $TERM and no -T specified``
``tput: No value for $TERM and no -T specified``
``  AddOn/german/vehicles/subway/BVB_E.dat``
``tput: No value for $TERM and no -T specified``
``tput: No value for $TERM and no -T specified``
``tput: No value for $TERM and no -T specified``
``  []   4%``
``  AddOn/german/vehicles/subway/BVG_E.dat``
``  []   9%``
``Error: Makeobj returned an error for AddOn/german/vehicles/subway/U-Bahn_Hamburg.dat. Aborting...``

Do you see the nuremberg subway trains?

**Comment by Leartin** [comment]
Sorry, did not see the AddOn-Label.

I'd start by changing the waytype in U-Bahn_Hamburg.dat, it's narrrowgauge with three r...

**Comment by Flemmbrav** [comment]
And they do not appear at all - neither the Hamburg nor the Nuremberg vehicles.

Was the last thing i saw yesterday, I should clarify that this is about the addon set.

**Comment by Flemmbrav** [comment]
https://github.com/Flemmbrav/Pak192.Comic/commit/b266bd3bb204278377d9b6cb163d0fba999cfe8d
fixes is.

`` Warning: Failed to get one or more hashes on AddOn/german/vehicles/track/BR03.10.dat
`` Error: Makeobj returned an error for AddOn/german/vehicles/track/BR03.10.dat. Aborting...

is next...
