### ISSUE TITLE
Possible Future Category Container Goods

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#38]
Splitting up the piece goods category, there have been ideas to split containers up from piece goods as well. You might take a look at this as well: https://github.com/Flemmbrav/Pak192.Comic/issues/15

The discussion resulted in a pretty detailed list of stuff we should find solutions for: https://github.com/Flemmbrav/Pak192.Comic/projects/12

**Comment by Flemmbrav** [comment]
> Do we have enough vehicles or can we make them reasonably quick?

Speaking for modern containers:
The only way we have enough vehicles for is the narrowgauge. We would need classic piece good vehicles for track and water. In plus, we'd need something to carry containers on for road.
In total this should result in at least:
- 1 classic piece goods car for track
- 1 classic piece goods ship
- 1 trailer for containers for road
just to capture modern day containers.
Out of these it should not be hard to create older vehicles as well, since most of the container vehicles are as plain as it gets.

> How to tackle the size issue?

I think we're good using a single size for all of them.
Standard-rail and narrowgauge kind of try to use the same size by now, and even though trucks might be slightly off, it should be looking just fine. Only kind of vehicles I'd be concerned off are ships. A ship is roughly 3 train cars long and 3 train cars wide. In heigth we could go with 3 (2 of them above water) as well, resulting in 27 train cars of goods, which is around one train for track and 3 trains for narrowgauge as well as 14 trucks. While this isn't exactly how it is in real life, it's still significantly more per vehicles than a car.

> How to deal with station capacity? Does one container take up as much space as one pallet?

I think this issue might be a thing with containers, but it is for cars too. We have cars as units, we can have containers as units too.
On the other hand, do you think it would be hard to patch individual amounts of occupied capacity for different kinds of goods?
Rolls could profit from this as well as cars too.

> Which units to use for container goods?

I think we should go with "container" as in 20ft containers (or 20ft Binnencontainer?).

**Comment by Leartin** [comment]
![Comparison Container](https://cdn.discordapp.com/attachments/349626891487150080/725649738602381403/Auflieger_Stueckgut_01.png)

I **really** don't think using a single size is a good idea.

**Comment by Citarofahrer** [comment]
Only Length are different. ISO Containers all have the same higth and width. Only 8" ISO COntainers are smaler lower, but the differences are such small.
I think the idea using 20ft containers as Unit would be fine, using 40ft Container Graphics would get 2 Units of 20ft Containers. Using an 80ft Sggns 80" would fit for 4 Units. 
https://www.lagerzeltverleih.com/wp-content/uploads/2019/03/lagercontainer-abmessungen.jpg

**Comment by Leartin** [comment]
So?

**Comment by Flemmbrav** [comment]
I'd like to suggest this size to fit them all:
![image](https://user-images.githubusercontent.com/44527862/89709010-3ebd8000-d97c-11ea-9503-4e6b75220e67.png)
![image](https://user-images.githubusercontent.com/44527862/89709075-db801d80-d97c-11ea-8e4b-7d8346e957ea.png)
This might seem a bit "weird" on the ship for first glance, but 20 containers are 10 cars for a train.
If you'd bring  the bridge to the front of the ship you might be able to hint 3 layers with 30 to 36 containers total.

**Comment by Flemmbrav** [comment]
https://github.com/Flemmbrav/Pak192.Comic/commit/5f86405c85ca577f9fa812f486f8b7037c403223 brought vehicles for the standard gauge track as well as three trucks. With that i also introduced containers. What's left is to create proper vehicles for the narrowgauge and a ship.

I'd love to see some feedback on how it turned out!
Also please check the balancing of the affected industries.

**Comment by Flemmbrav** [comment]
Seems like this is working fine by now
