### ISSUE TITLE
Invalid reference to parameter

### ISSUE THREAD

**Issue by ceeac** [Flemmbrav/Pak192.Comic#46]
https://github.com/Flemmbrav/Pak192.Comic/blob/15cba65e70463b7c6c5ba0e957a49697b041c00d/pakset/buildings/city/com_5alpine_2x2.dat#L86

This is probably an error since `$2` is not valid (there are only 2 parameter ranges on the left hand side so only `$0` and `$1` are valid on the right hand side).

**Comment by Flemmbrav** [comment]
Fixed it finally...
