### ISSUE TITLE
Translation for Containers

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#83]
The whole good has no translation. Not to mention the industry behind it.

**Comment by Roboron3042** [comment]
Importing the text(s) to the Simutranslator would help. There's someone who asked recently for an account to translate pak192.comic into English (but has made little progress so far).

**Comment by Flemmbrav** [comment]
Done with https://github.com/Flemmbrav/Pak192.Comic/commit/2e010aeac41d1f56499c0fe11d6bc75479c86ae2
