### ISSUE TITLE
Oil Rig can't trigger passenger bonus.

### ISSUE THREAD

**Issue by Roboron3042** [Flemmbrav/Pak192.Comic#85]
Okay, let's open a proper issue before we forget about this. The Oil Rig has passenger bonus, but it can't be triggered. This is because it has passenger/mail demand, but also the oilplatform station does not accept passengers/mail. So one of those two things need to change, right?

Linked Steam bug report https://steamcommunity.com/app/434520/discussions/1/3192488845081881526/

**Comment by Leartin** [comment]
Indeed. Any idea how to change the auto-spawning station to one that includes pax/mail?
