### ISSUE TITLE
The Dairy Problem

### ISSUE THREAD

**Issue by Leartin** [Flemmbrav/Pak192.Comic#89]
Currently, there is both a factory and a good called "Dairy". That's why the good is translated to German as "Käserei", same as the factory. While the Simutranslator probably holds both entries since it might know what type it is, the game only looks up the string. Either Good or Factory needs to be renamed.

**Comment by Flemmbrav** [comment]
I'd prefer renaming the factory.

**Comment by Flemmbrav** [comment]
should be done with https://github.com/Flemmbrav/Pak192.Comic/commit/372e1a25f37d1b59a62eb6ee67fd5a78091c5ab6
