### ISSUE TITLE
British AddOns do not compile

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#9]
Some images are missing, notably class 156 and class 158 variants.

**Comment by Flemmbrav** [comment]
Would it help to just remove the missing things?

**Comment by Citarofahrer** [comment]
Are those the only 2 Addons?

**Comment by Flemmbrav** [comment]
I'm not sure yet, these are the first ones to not compile. After that the compiler stops, thus there could be more

**Comment by Citarofahrer** [comment]
can you evaluate witch are all missing?

**Comment by Leartin** [comment]
Following dats do not compile properly:
Class 156 EMT (no image, made .dat a .txt)
Class_158_ASR_2 (BR_Class_158_ASR_H not available, placeholder BR_Class_158_ASR_F used, please fix ASAP)
BR_Class_159_SWT_H (image falsely named "BR_Class_158_SWT_H")
BW-Wagen (someone was dumb enough to use '+' in a filename)
E231-500 (script expected subfolders; changed script)
Script completes now - no functional test though.

**Comment by Flemmbrav** [comment]
Thanks a lot, the BW-Wagen did work locally x)

**Comment by vzrenggamani** [comment]
This is still opened or have been closed ?

**Comment by Leartin** [comment]
I left it open for Class 158 which Flemmbrav fixed, now it's only Class 156 which is so minor, I close this now.
