### ISSUE TITLE
Lists of all vehicles and depots

### ISSUE THREAD

**Issue by Flemmbrav** [Flemmbrav/Pak192.Comic#95]
"The pak192.comic doesn't have icons for these lists yet, hopefully that will change in the next version.  :P"
https://forum.simutrans.com/index.php/topic,21499.0.html

**Comment by Leartin** [comment]
Thanks for pointing that out, latest commit should fix it. Please confirm.

**Comment by Flemmbrav** [comment]
![image](https://user-images.githubusercontent.com/44527862/202876473-bdabbaff-1e21-4d3c-bf13-a69adf07f1c8.png)
While the icon doesn't seem to fit, the functionality seems to work.

**Comment by Flemmbrav** [comment]
Works now
